# Generated by Django 4.0.4 on 2022-05-31 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=40)),
                ('ciudad_id_ciudad', models.ForeignKey(db_column='ciudad_id_ciudad', on_delete=django.db.models.deletion.CASCADE, to='miapp.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tiproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tiproducto', models.CharField(max_length=20)),
                ('descrip_tiproducto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo_usuario', models.CharField(max_length=50, unique=True)),
                ('nombre_usuario', models.CharField(max_length=25, unique=True)),
                ('pass_usuario', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=60)),
                ('dir_envio_default', models.CharField(max_length=60)),
                ('fono_usuario', models.CharField(max_length=12)),
                ('comuna_id_comuna', models.ForeignKey(db_column='comuna_id_comuna', on_delete=django.db.models.deletion.CASCADE, to='miapp.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=12, unique=True)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('descrip_producto', models.CharField(max_length=200)),
                ('precio_producto', models.IntegerField()),
                ('stock_producto', models.CharField(max_length=40)),
                ('fecha_agregado', models.DateField()),
                ('tipo_producto_id_tiproducto', models.ForeignKey(db_column='tipo_producto.id_tiproducto', on_delete=django.db.models.deletion.CASCADE, to='miapp.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('direccion_envio', models.CharField(max_length=60)),
                ('direccion_pedido', models.CharField(max_length=60)),
                ('correo_pedido', models.CharField(max_length=50)),
                ('fecha_pedido', models.DateField()),
                ('estado_pedido', models.CharField(max_length=20)),
                ('usuario_comuna_id_comuna', models.ForeignKey(db_column='usuario_comuna_id_comuna', on_delete=django.db.models.deletion.CASCADE, related_name='idComunaEnUsuario', to='miapp.usuario')),
                ('usuario_id_usuario', models.ForeignKey(db_column='usuario_id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='idUsuarioEnPedido', to='miapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_pedido', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('pedido_id_pedido', models.ForeignKey(db_column='pedido_id_pedido', on_delete=django.db.models.deletion.CASCADE, to='miapp.pedido')),
                ('producto_id_producto', models.ForeignKey(db_column='producto_id_producto', on_delete=django.db.models.deletion.CASCADE, to='miapp.producto')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='region_id_region',
            field=models.ForeignKey(db_column='region_id_region', on_delete=django.db.models.deletion.CASCADE, to='miapp.region'),
        ),
    ]
