# Generated by Django 4.0.4 on 2022-06-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='miniatura',
            field=models.ImageField(null=True, upload_to='products'),
        ),
    ]
