# Generated by Django 4.0.4 on 2022-06-08 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_producto_miniatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='usuario_comuna_id_comuna',
            new_name='id_comuna',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='usuario_id_usuario',
            new_name='id_usuario',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='tipo_producto_id_tiproducto',
            new_name='id_tiproducto',
        ),
    ]
